# Generated by Django 5.0.10 on 2025-02-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
